### ISSUE TITLE
git clone报错

### ISSUE THREAD

**Issue by qingfengfeixin** [deepnighttwo/LetsJava#1]
在git clone的时候出现以下报错，无法clone仓库 win10操作系统

$ git clone https://github.com/geektime-geekbang/LetsJava.git                                                                            Cloning into 'LetsJava'...                                                                                                               remote: Enumerating objects: 316, done.                                                                                                  remote: Counting objects: 100% (316/316), done.                                                                                          remote: Compressing objects: 100% (188/188), done.                                                                                       remote: Total 316 (delta 58), reused 306 (delta 50), pack-reused 0                                                                       Receiving objects: 100% (316/316), 1.03 MiB \| 840.00 KiB/s, done.                                                                        Resolving deltas: 100% (58/58), done.                                                                                                    fatal: cannot create directory at '绗簩绔▒ Java闈㈠悜瀵硅薄缂栫▼ /01. 绫▒ (Clas                                                         s)': No such file or directory                                                                                                           warning: Clone succeeded, but checkout failed.                                                                                           You can inspect what was checked out with 'git status'                                                                                   and retry the checkout with 'git checkout -f HEAD'
--

**Comment by deepnighttwo** [comment]
抱歉, 我的错误. 我今天会改正好.

**Comment by qingfengfeixin** [comment]
已解决。
