### ISSUE TITLE
感觉反序列化内容不见了？

### ISSUE THREAD

**Issue by viewer2018** [deepnighttwo/LetsJava#3]
老师，您好，现在课程内容中，为啥会缺少反序列化的内容呢？

**Comment by deepnighttwo** [comment]
是的，和我当时写书的时候相比，Java的生态出现了非常多的序列化反序列化的框架，比如 Avro，Protobuf，Thrift。甚至JSON也非常普遍的用在Java对象的序列化和反序列化。

所以在这门课程中，我把Serializable接口和Java内置的对象系列化和反序列化的内容省略了。因为现在选择太多了，Serializable接口确实不是很实用。而且Java自带的序列化，非常非常慢。

就像我昨天在在直播里说的，我和极客时间的编辑正在筹划给课程扩充一些进阶的内容。Serializable接口这部分内容可以计划包含在内。现在使用Serializable接口的一般都是一些计算平台和框架，比如Spark就是使用这个接口，将mapper操作的对象序列化并传输给每个分布式计算进程的。

尽情期待～

**Comment by viewer2018** [comment]
非常期待
