### ISSUE TITLE
两个 byte 相加，返回值的类型是int

### ISSUE THREAD

**Issue by gaokechen** [deepnighttwo/LetsJava#4]
两个 byte 相加，返回值的类型并不是byte而是int，需要强制转换成byte。并且可能会超出数据有效范围出现异常值。
![微信截图_20200626205929](https://user-images.githubusercontent.com/32739652/85859613-06a91600-b7f0-11ea-83b5-e6eb0c99eed8.png)
![微信截图_20200626205518](https://user-images.githubusercontent.com/32739652/85859629-0c9ef700-b7f0-11ea-9d14-2a7e73515baa.png)

**Comment by deepnighttwo** [comment]
谢谢指出这里的错误，去JLS里查找了以下，果然是有这样的说明的

https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.6.2


   1.

   Widening primitive conversion (§5.1.2
   <https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.1.2>)
   is applied to convert either or both operands as specified by the following
   rules:
   -

      If either operand is of type double, the other is converted to double.
      -

      Otherwise, if either operand is of type float, the other is converted
      to float.
      -

      Otherwise, if either operand is of type long, the other is converted
      to long.
      -

      Otherwise, both operands are converted to type int.


我会联系编辑看如何进行修正。



gaokechen <notifications@github.com> 于2020年6月26日周五 下午9:04写道：

**Comment by gaokechen** [comment]
专业👍👍👍

**Comment by deepnighttwo** [comment]
已经联系编辑同学了，极客时间的编辑同学会帮忙作出相应的修改的。谢谢～

**Comment by deepnighttwo** [comment]
视频和ppt已经修正，closing。
